language: go

go:
  - 1.8

git:
  depth: 3

branches:
  only:
    - master

addons:
  apt:
    packages:
      - python-pygments

install:
  - go get -v github.com/gohugoio/hugo
  - rm -rf public || exit 0

script:
  - hugo version
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN} # Set in travis-ci.org dashboard
  repo: chchwy/chchwy.github.io
  target_branch: master
  local_dir: "public"
  on:
    branch: master