language: go

go:
  - 1.7

git:
  depth: 10

branches:
  only:
    - master

addons:
  apt:
    sources:
      - sourceline: 'ppa:rikmills/artful'
    packages:
      - hugo

install:
  - rm -rf public || exit 0

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN} # Set in travis-ci.org dashboard
  repo: chchwy/chchwy.github.io
  target_branch: master
  local_dir: "public"
  on:
    branch: master