language: go

go:
  - 1.9

git:
  depth: 2

branches:
  only:
    - master

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.deb
  - pwd
  - ls
  - sudo dpkg -i ./hugo_0.49_Linux-64bit
  - rm hugo_0.49_Linux-64bit.deb
  - rm -rf public || exit 0

script:
  - which hugo
  - hugo version
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN} # Set in travis-ci.org dashboard
  repo: chchwy/chchwy.github.io
  target_branch: master
  local_dir: "public"
  on:
    branch: master
