
baseurl: http://chchwy.github.io/

languageCode: zh-TW

#permalinks:
#  post:  /:year/:month/:filename/

title: "調和的靈感"

params:
  Subtitle:   "{ Matt, chchwy }"
  Author:     "chchwy"
  GithubUser: "chchwy"
  google_analytics: UA-5266256-5

disqusShortname: "chchwy"