baseurl = "http://chchwy.github.io"
languageCode = "zh-TW"
title = "Matt | 調和的靈感"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/mgjohansen\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
disqusShortname = "chchwy"
googleAnalytics = "UA-5266256-5"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "My blog"
keywords = ["chchwy", "Matt Chang", "C++", "3D Graphics"]
author = "Matt Chang"
sharingicons = true
displayauthor = true

[params.highlight]
style = "github"
languages = ["c++", "xml"]

[[params.social]]
url = "https://github.com/chchwy"
fa_icon = "fa-github"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"